Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -29,20 +29,28 @@ jobs:
             -Dsonar.organization=fastapidemonstracao
 
   build-and-push:
+    name: Build and Push Docker Image
     runs-on: ubuntu-22.04
     needs: sonarcloud
     steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+      
       - name: Login to Docker Hub
-        uses: docker/login-action@v1
+        uses: docker/login-action@v2
         with:
           username: ${{ secrets.name }}
           password: ${{ secrets.secret }}
 
       - name: Display Dockerfile
-        run: cat Dockerfile
+        run: |
+          if [ -f Dockerfile ]; then
+            cat Dockerfile
+          else
+            echo "Dockerfile not found!"
+            exit 1
+          fi
 
-      - uses: actions/checkout@v2
-      
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
@@ -57,10 +65,11 @@ jobs:
         run: docker push julianobcgato/projetocompass:${{ github.run_number }}
 
   alterar_tag:
+    name: Update Deployment YAML
     runs-on: ubuntu-latest
     needs: build-and-push
     steps:
-      - name: Checkout Repository
+      - name: Checkout Repository for GitOps
         uses: actions/checkout@v3
         with:
           repository: julianobcgato/code
@@ -70,7 +79,13 @@ jobs:
         run: echo "RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
 
       - name: Display deployment.yaml
-        run: cat ./gitops/deployment.yaml
+        run: |
+          if [ -f ./gitops/deployment.yaml ]; then
+            cat ./gitops/deployment.yaml
+          else
+            echo "deployment.yaml not found!"
+            exit 1
+          fi
 
       - name: Modify yaml File
         run: |
@@ -81,7 +96,7 @@ jobs:
           git config user.name "Juliano"
           git config user.email "julianobcgato@gmail.com"
           git add ./gitops/deployment.yaml
-          git commit -m "Update image tag in values.yaml"
+          git commit -m "Update image tag in deployment.yaml"
           git push
 
 
